version: 1.0.{build}
image: Visual Studio 2017
init:
    - git config --global core.autocrlf input
environment:
  COVERALLS_REPO_TOKEN:
    secure: Kr66k5+0ZIgStoWrrdVxfwRe44NvCOQ2bV+94poeF3rKbxKBYqQZkfrv1jSK0q5+
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  CoverWith: OpenCover
  PreReleaseSuffix: alpha
  GitUser:
    secure: zAdAOUUof3XGDsdOBRYg7J7wZS44iL4VjI/MVGw+JnU=
  GitOwner:
    secure: n6W5JZ7Q/xfZC7b2k3+ORA==
  GitPassword:
    secure: fHangGPAk14u3V1eP3kg5EdekQoKdOsKC0F/A1mvh9IODHCZ92FGjfWb0U2aQ8bu
build_script:
- ps: .\build.ps1 -Target AppVeyor
test: off
artifacts:
- path: artifacts/packages/*.nupkg
- path: artifacts/coverage/*.xml
- path: artifacts/test-results/*.trx
- path: artifacts/resharper-reports/*.xml
- path: artifacts/resharper-reports/*.html
- path: artifacts/coverage/coverage.dcvr
deploy:
- provider: NuGet
  server: https://www.myget.org/F/appmetrics/api/v2/package
  api_key:
    secure: gIAiACgNj+JzXyLLTe3rLxZyrAB9RpC8Lw81xEjdOLXqotprqEwGiFWRipEqkpps
  skip_symbols: true
  symbol_server: https://www.myget.org/F/appmetrics/symbol
install:
  - cmd: curl -O https://download.microsoft.com/download/A/B/1/AB1AA972-8F2F-43AD-9A81-72E9245CB0F5/dotnet-runtime-2.1.0-preview1-26216-03-win-x64.exe
  - cmd: dotnet-runtime-2.1.0-preview1-26216-03-win-x64.exe /install /quiet /norestart /log install.log
skip_commits:
  files:    
    - '**/*.md'